//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int idContract { get; set; }
        public System.DateTime dateRegistration { get; set; }
        public int idOfficer { get; set; }
        public int idCustomer { get; set; }
        public int idVehicle { get; set; }
        public int idParkingCard { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Officer Officer { get; set; }
        public virtual ParkingCard ParkingCard { get; set; }
        public virtual Verhicle Verhicle { get; set; }
    }
}
