//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GarageManagementEntities : DbContext
    {
        public GarageManagementEntities()
            : base("name=GarageManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<GarageStaff> GarageStaffs { get; set; }
        public virtual DbSet<Officer> Officers { get; set; }
        public virtual DbSet<ParkingCard> ParkingCards { get; set; }
        public virtual DbSet<VehicleStatu> VehicleStatus { get; set; }
        public virtual DbSet<Verhicle> Verhicles { get; set; }
        public virtual DbSet<VerhicleCategory> VerhicleCategories { get; set; }
    }
}
