//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Officer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Officer()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int idOfficer { get; set; }
        public string emailOfficer { get; set; }
        public string nameOfficer { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public int idAdmin { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
