//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleStatu()
        {
            this.ParkingCards = new HashSet<ParkingCard>();
        }
    
        public int idVehicleStatus { get; set; }
        public string nameStatus { get; set; }
        public System.DateTime timeInputAndOutput { get; set; }
        public int idGarageStaff { get; set; }
    
        public virtual GarageStaff GarageStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingCard> ParkingCards { get; set; }
    }
}
