//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verhicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Verhicle()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int idVerhicle { get; set; }
        public string licensePlate { get; set; }
        public string vehicleRegistration { get; set; }
        public string describe { get; set; }
        public int idVehicleCategory { get; set; }
        public int idCustomer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual VerhicleCategory VerhicleCategory { get; set; }
    }
}
