//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerhicleCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VerhicleCategory()
        {
            this.Verhicles = new HashSet<Verhicle>();
        }
    
        public int idVehicleCategory { get; set; }
        public string nameVehicleCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verhicle> Verhicles { get; set; }
    }
}
